### ISSUE TITLE
Add support for audio output

### ISSUE THREAD

**Issue by KnightMustard** [Elerir/NV-Broadcast-Autotoggle#1]
Add support to toggle audio output for nvidia broadcast.

**Comment by Elerir** [comment]
Hi,

Would it be okay if it acts the same way as it actually does with audio input ?

**Comment by KnightMustard** [comment]
Yeah, I think the same concept works.

**Comment by Elerir** [comment]
Alright,
Sorry for the delay, I started working on it
I'll try to finish this before monday

**Comment by Elerir** [comment]
Alright as you noticed I was not active these last weeks.
Is that still needed ? Didn't finish yet but I'll try to really find time to do it

**Comment by KnightMustard** [comment]
Hello, sorry for the delay. Yeah this is still an issue for me. I can't truly schedule disabling both input and output currently.

**Comment by Elerir** [comment]
Hello,
I just implemented this feature 
e71ffddae87619ef81c46939b4d63ed1c35c6132
Feel free to tell me if there is an issue

1. Clone the "[dev-RTXVoiceCompatibility](https://github.com/Elerir/NV-Broadcast-Autotoggle/tree/dev-RTXVoiceCompatibility)" branch
2. Modify "TemplateNvidiaBroadcastController.ps1" file to suit your needs (set $enableSpeakersDenoising to $True)
3. Execute install.ps1
